### ISSUE TITLE
Zeitwerk check incompatibility

### ISSUE THREAD

**Issue by uncoverd** [infinum/rails-infinum-mailgun_catcher#5]
The official Rails 6 upgrade guide [suggests](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading) that we check the new autoloading compatibility by executing `rake zeitwerk:check`.

The implementation of the Rails rake task
https://github.com/rails/rails/blob/f4a04c3ca49c99288756bb92e83a574efacf197f/railties/lib/rails/tasks/zeitwerk.rake#L56-L58

checks each namespace

```ruby
[5] pry(main)> Rails.configuration.eager_load_namespaces
=> [ActiveSupport,
 ActionDispatch,
 ActiveModel,
 GlobalID,
 ActionView::Railtie,
 ActionView,
 ActionController,
 ActiveRecord,
 ActionMailer,
 ActionCable::Engine,
 ActionCable,
 Sidekiq::Rails,
 Cocoon::Engine,
 Config::Integrations::Rails::Engine,
 Devise::Engine,
 DeviseInvitable::Engine,
 Jquery::Rails::Engine,
 Kaminari::Engine,
 MailgunCatcher::Engine,
 MoneyRails::Engine,
 SimpleForm,
 Turbolinks::Engine,
 Webpacker::Engine,
 MyApplication::Application]
```
if it responds to `config`, since it expects a `Rails::Application::Configuration` to be returned.
```ruby 
[9] pry(main)> MyApplication::Application.config.class
=> Rails::Application::Configuration
``` 

Since MailgunCatcher responds to `:config`, but returns a different type of object
```ruby
[6] pry(main)> MailgunCatcher::Engine.config
=> #<#<Class:0x00007f93c5b69968>:0x00007f93c5b69738 @config={:webhooks_path=>"webhooks"}>
```
which doesn't have `eager_load_paths`defined we get a `NoMethodError`.

```
 ✘ jaka@Jakas-MacBook-Pro  ~/Work/web-loop-community-backend   feature/rails-6-upgrade ●  bundle exec rake zeitwerk:check --trace
** Invoke zeitwerk:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute zeitwerk:check
Hold on, I am eager loading the application.
rake aborted!
NoMethodError: undefined method `eager_load_paths' for #<#<Class:0x00007f9c615ab5b8>:0x00007f9c615ab388>
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/tasks/zeitwerk.rake:57:in `block (3 levels) in <main>'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/tasks/zeitwerk.rake:56:in `map'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/tasks/zeitwerk.rake:56:in `block (2 levels) in <main>'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bugsnag-6.6.4/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/jaka/.rbenv/versions/2.6.5/bin/rake:23:in `load'
/Users/jaka/.rbenv/versions/2.6.5/bin/rake:23:in `<top (required)>'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/jaka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/Users/jaka/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/jaka/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => zeitwerk:check
```

**Comment by d4be4st** [comment]
This is fixed in https://github.com/infinum/rails-infinum-mailgun_catcher/commit/4db808fe024321b0218230915e85b3caaaa4c535
